#!/usr/bin/env bash

set -euo pipefail

url=http://metaphorpsum.com

if [ $# -ne 2 ]; then
  echo "Usage: lorem [p (paragraphs), s (sentences)] [integer]"
	exit 20
fi

if [[ "${1}" = "p" || "${1}" = "paragraphs" ]]; then
	curl -s ${url}/paragraphs/${2}
fi

if [[ "${1}" = "s" || "${1}" = "sentences" ]]; then
	curl -s ${url}/sentences/${2}
fi

echo
